services:
  db:
    image: postgres:13
    restart: always
    container_name: jira-clone-db
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: dumi
      POSTGRES_PASSWORD: dumi
      POSTGRES_DB: jira-clone-db
