services:
  db:
    image: postgres:13
    restart: always
    container_name: jira-clone-db-test
    ports:
      - "5439:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: jira-clone-db-test
    volumes:
      - jira-clone-db-test:/var/lib/postgresql/data
volumes:
  jira-clone-db-test:
